/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kingseiya_ilmito_EasyRpgPlayerActivity */

#ifndef _Included_com_kingseiya_ilmito_player_EasyRpgPlayerActivity
#define _Included_com_kingseiya_ilmito_player_EasyRpgPlayerActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_kingseiya_ilmito_player_EasyRpgPlayerActivity_COMMAND_CHANGE_TITLE
#define com_kingseiya_ilmito_player_EasyRpgPlayerActivity_COMMAND_CHANGE_TITLE 1L
#undef com_kingseiya_ilmito_player_EasyRpgPlayerActivity_COMMAND_UNUSED
#define com_kingseiya_ilmito_player_EasyRpgPlayerActivity_COMMAND_UNUSED 2L
#undef com_kingseiya_ilmito_player_EasyRpgPlayerActivity_COMMAND_TEXTEDIT_HIDE
#define com_kingseiya_ilmito_player_EasyRpgPlayerActivity_COMMAND_TEXTEDIT_HIDE 3L
#undef com_kingseiya_ilmito_player_EasyRpgPlayerActivity_COMMAND_USER
#define com_kingseiya_ilmito_player_EasyRpgPlayerActivity_COMMAND_USER 32768L
/*
 * Class:     com_kingseiya_ilmito_EasyRpgPlayerActivity
 * Method:    toggleFps
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kingseiya_ilmito_player_EasyRpgPlayerActivity_toggleFps
  (JNIEnv *, jclass);

/*
 * Class:     com_kingseiya_ilmito_EasyRpgPlayerActivity
 * Method:    endGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kingseiya_ilmito_player_EasyRpgPlayerActivity_endGame
  (JNIEnv *, jclass);

/*
 * Class:     com_kingseiya_ilmito_EasyRpgPlayerActivity
 * Method:    setFastForwardMultiplier
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kingseiya_ilmito_player_EasyRpgPlayerActivity_setFastForwardMultiplier
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
